### PR TITLE
Fixed some waypoints

### PR DESCRIPTION
**Pull request by GaryTheNoTrashCougar**
Fixed some known bot stuck wps & made improvements on some maps (Arkaden, Bakaara, Bootleg, Carbon, Dome, Lockdown, Mission, Resistance, Seatown, Favela & Nuketown) & added in some new ones.

### CODE REVIEW

**Comment by megvadulthangya** [comment]
Hi! Can i ask where is those waypoints? 
Couse i dont find repo for piw5_bot_warfare ... and looks like nuketown is having lot of stuckages... 
Pls help!

**Comment by GaryTheNoTrashCougar** [comment]
Forked in my repositories. I will have a look at Nuketown way points. Probably won't be for a couple days though.

**Comment by GaryTheNoTrashCougar** [comment]
Done it now, not tested but should be better.  Let me know if they're still getting stuck anywhere.  Thanks

**Comment by megvadulthangya** [comment]
> Forked in my repositories. I will have a look at Nuketown way points. Probably won't be for a couple days though.

I feel stupid myself... i dont find just this:
https://github.com/GaryTheNoTrashCougar/piw5_bot_warfare
But i dont see waypoints
Maybe not public ? 
Can you give me link?

**Comment by GaryTheNoTrashCougar** [comment]
Don't do mods folder install, just copy maps & scripts folders from raw folder into C:\users\<yourusername>\AppData\Local\Plutonium\storage\iw5

**Comment by megvadulthangya** [comment]
Wow! Thank you!
I used the out iwd originally... I dont even noticed the folder in raw which is full of waypoints
I guess dont need to load mods/bots this way

**Comment by GaryTheNoTrashCougar** [comment]
Ok, I will update this when I get home.  For now you can open iwd as archive (you will need a program to do this, a Linux version of 7zip will work) then replace the waypoint files with the ones from my repository.

**Comment by megvadulthangya** [comment]
You dont need to do anything, i use Total commander for that i can edit the files in the IWD. 
I created a zip from your whole raw folder (without bw-assets) then renamed to iwd

**Comment by GaryTheNoTrashCougar** [comment]
Has this worked for you?

**Comment by megvadulthangya** [comment]
> Has this worked for you?

I can add 5-6 maps which is not worked before this, so yeah no crash, and bots are find his ways. So Thank you!

**Comment by Shepherddidnothingwrong** [comment]
Do you have plans to fix Liberation? That map is really prone to lag and stuttering after playing a while with 17 bots. Most definitely due to some bad or excessive waypoints.

**Comment by GaryTheNoTrashCougar** [comment]
I will get round to every map eventually.  I thought I did an OK job of what I've done so far but after playing with them for a while longer there are still some issues.  I may have gone overkill myself with some waypoints, just trying to make the bots seem less predictable by giving them more route choices.  There is a slight issue when pots are sprinting & a waypoint turn is tight, they go off course & can potentially get stuck.  Might ask dev if there is any way to add more waypoint types so we can force bots to walk in certain areas, turn around on path (so you can make them drop off a ledge that they wouldn't be able to climb up & get stuck) or even have the ability to jump to make it to areas you can only jump across to.

**Comment by megvadulthangya** [comment]
you can contact ineedbots? He never answered me, i wrote him mail and wrote
in modb...
His pt6_bot_warfare repo is missing a lot of files...


Gary Cougar ***@***.***> ezt írta (időpont: 2022. jan. 27.,
Cs, 17:22):

**Comment by GaryTheNoTrashCougar** [comment]
No, sorry. Probably just very busy, give it time.

**Pull request merged**
